/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ezen.academy;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;

public class Main {
    public static void main(String[] args)throws IOException{
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(System.out));
        StringBuilder sb = new StringBuilder();
        int sum = 0;
        int size = Integer.parseInt(br.readLine());
        String str = br.readLine();
        for(int i = 0; i < size; i++){
            sum += str.charAt(i)-'0';
        }
        sb.append(sum);

        bw.write(sb.toString());
        bw.flush();
        bw.close();
        br.close();
    }
}