/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ezen.academy;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

// class Person{
//     String name;
//     String id;

//     Person(String name){
//         this.name=name;
//     }
// }

// class Student extends Person{
//     String grade;

//     Student(String name){
//         super(name);
//     }
// }

// class Music{
//     String title;
//     String singer;

//     Music(String title){
//         this(title,"방탄");
//     }
//     Music(String title, String singer){
//         this.title = title;
//         this.singer = singer;
//     }
// }

// class Cal{
//     int add(int a, int b){
//         return a+b;
//     }
//     int div(int a, int b){
//         return a/b;
//     }
// }

// abstract class Car{
//     String name;

//     void run(){
//         System.out.println("차가 움직인다.");
//     }
//     abstract void stop();
// }

// class Cars extends Car{
//     Cars(){
//         name="인피니티";
//     }
//     @Override
//     void stop(){
//         System.out.println("차가 멈춘다.");
//     }
// }

// class Tv{
//     String brand;
//     int year;
//     int inch;
//     Tv(String brand, int year, int inch){
//         this.brand = brand;
//         this.inch = inch;
//         this.year = year;
//     }

//     void show(){
//         System.out.println(year+"년에 "+brand+"에서 나온 "+inch+"인치 TV");
//     }
// }

// class Score{
//     int math;
//     int eng;
//     int com;

//     double avg(){
//         return (math+eng+com)/3.0;
//     }
// }

public class Main {
    public static void main(String[] args)throws IOException{
        // Cars car = new Cars();
        // car.run();
        // car.stop();

        // String eng[] = {"student","book","future","note"};
        // String kor[] = {"학생","책","미래","노트"};

        // BufferedReader br = new BufferedReader(new InputStreamReader(System.in));

        // while(true){
        //     System.out.print("영어 단어 입력 : ");
        //     String str = br.readLine();
        //     if(str.equals("stop")){
        //         break;
        //     }
        //     for(int i = 0; i < eng.length; i++){
        //         if(eng[i].equals(str)){
        //             System.out.println(kor[i]);
        //         }
        //     }
        // }
    }

    // static int get(int[][] numArr){
    //     int max = 0;

    //     for(int i = 0; i < numArr.length; i++){
    //         for(int j = 0; j < numArr[i].length; j++){
    //             if(max<numArr[i][j]) max = numArr[i][j];
    //         }
    //     }
    //     return max;
    // }
}