/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ezen.academy;

import java.io.IOException;
import java.util.Scanner;

// class Circle {
//     private double r;

//     Circle(double r) {
//         this.r = r;
//     }

//     double area() {
//         return 3.14 * r * r;
//     }
// }
// class XY{
//     int x;
//     int y;

//     void set(int x, int y){
//         this.x=x;
//         this.y=y;
//     }

//     void show(){
//         System.out.println(x+","+y);
//     }
// }
// class XYZ extends XY{
//     String color;
//     void color(String color){
//         this.color = color;
//     }
// }


public class Main {
    public static void main(String[] args) throws IOException {
       
       
       
       
        // System.out.print("나 : ");
        // Scanner scan = new Scanner(System.in);
        // String rsp = scan.nextLine();
        // int rand = (int)(Math.random()*3);
        
        // if(rand==0)
        // {
        //     if(rsp.equals("가위")){
        //         System.out.println("철수 : 가위");
        //         System.out.println("비겻다");
        //     }else if(rsp.equals("바위")){
        //         System.out.println("철수 : 가위");
        //         System.out.println("이겻다");
        //     }else{
        //         System.out.println("철수 : 가위");
        //         System.out.println("졋다");
        //     }
        // }else if(rand==1){
        //     if(rsp.equals("가위")){
        //         System.out.println("철수 : 바위");
        //         System.out.println("졋다");
        //     }else if(rsp.equals("바위")){
        //         System.out.println("철수 : 바위");
        //         System.out.println("비겻다");
        //     }else{
        //         System.out.println("철수 : 바위");
        //         System.out.println("이겼다");
        //     }
        // }else{
        //     if(rsp.equals("가위")){
        //         System.out.println("철수 : 보");
        //         System.out.println("이겼다");
        //     }else if(rsp.equals("바위")){
        //         System.out.println("철수 : 보");
        //         System.out.println("졌다");
        //     }else{
        //         System.out.println("철수 : 보");
        //         System.out.println("비겼다");
        //     }
        // }
        
        
        
        // XY x= new XY();
        // x.set(1,2);
        // x.show(); //1,2 출력
        // XYZ xy=new XYZ();
        // xy.set(4,5);
        // xy.color("blue");
        // xy.show(); //4,5,blue 출력 
        
        
        
        // BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        // BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(System.out));
        // StringBuilder sb = new StringBuilder();
        // int[] numArr = new int[10];

        // for(int i = 0; i < numArr.length; i++){
        //     numArr[i] = Integer.parseInt(br.readLine());
        // }

        // Arrays.sort(numArr);
        // sb.append("[ ");
        // for(int i = 0; i < numArr.length; i++){
        //     sb.append(numArr[i]).append(" ");
        // }
        // sb.append(']');
        // bw.write(sb.toString());
        // bw.flush();
        // bw.close(); 
        // br.close();



        
        // Circle[] circles = new Circle[5];
        // BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        // BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(System.out));

        // double sum = 0;

        // for (int i = 0; i < circles.length; i++) {
        //     circles[i] = new Circle(Double.parseDouble(br.readLine()));
        //     sum += circles[i].area();
        // }
        // bw.write(String.valueOf(sum));
        // bw.flush();
        // bw.close();
        // br.close();
    }

}