/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ezen.academy;

import java.io.IOException;
import java.util.Scanner;

interface Animal{
    public void bear();
}

interface Fish{
    public void swim();
}

class Test implements Animal, Fish{
    @Override
    public void bear(){
        System.out.println("낳는다");
    }
    @Override
    public void swim(){
        System.out.println("수영한다");
    }
}

// interface Food{
//     public String name();
// }

// class Pizza implements Food{
//     @Override
//     public String name(){
//         return "피자";
//     }
// }

// class Steak implements Food{
//     @Override
//     public String name(){
//         return "스테이크";
//     }
// }

public class Main {

    // static void pr (Food f){
    //     System.out.println(f.name());
    // }
    public static void main(String[] args) throws IOException {
    Test a = new Test();
    a.bear();
    a.swim();
    
    
    
    //    pr(new Pizza());
    //    pr(new Steak());
    }

}