/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ezen.academy;

import java.io.IOException;

// abstract class Profile {
//     abstract void add(String name, String id);

//     abstract String check(String id);
// }

// class Person {
//     String name;
//     String id;

//     Person(String name, String id) {
//         this.name = name;
//         this.id = id;
//     }

//     public String getName() {
//         return this.name;
//     }

//     public String getId() {
//         return this.id;
//     }
// }

// class Per extends Profile {

//     Person[] ary;
//     int n;

//     Per(int n) {
//         ary = new Person[n];
//     }

//     @Override
//     void add(String name, String id) {
//         ary[n] = new Person(name, id);
//     }

//     @Override
//     String check(String id) {
//         for (int i = 0; i < n; i++) {
//             if (id.compareTo(ary[i].getId()) == 0) {
//                 return ary[i].getName();
//             }
//         }
//         return null;
//     }

// }

// class Java {
//     String title;

//     Java(String title) {
//         this.title = title;
//     }

//     void show() {
//         System.out.println(this.title);
//     }
// }

// class DB {
//     int n;

//     DB(int n) {
//         this.n = n;
//     }

//     void pr() {
//         System.out.println(n);
//     }
// }

// class Program<T> {
//     T t;

//     void in(T t) {
//         this.t = t;
//     }

//     T get() {
//         return t;
//     }
// }

// interface Cal{
//     int total(int a, int b);
//     int big(int a, int b);
// }

// class Calcu implements Cal{
//     public int total(int a, int b){
//         return a+b;
//     }
//     public int big(int a, int b){
//         return a>b?a:b;
//     }
// }

// class Th extends Thread {
//     String name;

//     Th(String name) {
//         this.name = name;
//     }

//     @Override
//     public void run() {
//         System.out.println(name);
//     }
// }

// class Timer extends Thread {
//     @Override
//     public void start() {
//         for (int i = 0; i <= 10; i++) {
//             try {
//                 System.out.println(i);
//                 sleep(1000);
//             } catch (InterruptedException e) {
//                 // TODO Auto-generated catch block
//                 e.printStackTrace();
//             }
//         }
//     }
// }

// class Total {
//     int sum;

//     Total() {
//         sum = 0;
//     }

//     void total(int n) {
//         sum += n;
//     }

//     int get() {
//         return sum;
//     }
// }

// class AThread extends Thread {
//     Total t;
//     int start;
//     int end;

//     AThread(Total t, int start, int end) {
//         this.t = t;
//         this.start = start;
//         this.end = end;
//     }

//     @Override
//     public void run() {
//         for (int i = start; i <= end; i++) {
//             t.total(i);
//             System.out.println(t.get());
//         }
//     }
// }

// interface Figure {

//     void circle_area();

//     void rec_area();

// }

// class Circle implements Figure {
//     int r;

//     Circle(int r) {
//         this.r = r;
//     }

//     public void circle_area() {
//         System.out.println(r * r * 3.14);
//     }

//     @Override
//     public void rec_area() {
//     }
// }

// class Rec implements Figure {
//     int x, y;

//     Rec(int x, int y) {
//         this.x = x;
//         this.y = y;
//     }

//     public void rec_area() {
//         System.out.println(x * y);
//     }

//     @Override
//     public void circle_area() {
//     }
// }

public class Main {

    public static void main(String[] args) throws IOException {
        // Figure f1 = new Circle(5);
        // Figure f2 = new Rec(2, 5);
        // f1.circle_area();
        // f2.rec_area();

        // Total t = new Total();
        // AThread a = new AThread(t, 1, 50);
        // AThread b = new AThread(t, 51, 100);

        // try {
        // a.start();
        // a.join();
        // b.start();
        // b.join();
        // } catch (Exception e) {
        // // TODO: handle exception
        // }

        // Timer t = new Timer();
        // t.start();

        // Th t = new Th("쓰레드 1");
        // Thread th = new Thread(t);
        // th.start();

        // Program<Java> p = new Program<Java>();
        // p.in(new Java("java"));
        // Java j = p.get();
        // j.show();

        // Profile profile = new Per(5);
    }

}