/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ezen.academy;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStreamWriter;
import java.util.StringTokenizer;

// class Person implements Serializable {
//     String name;
//     String subject;
//     int age;
//     int num;

//     public Person(String name, String subject, int age, int num) {
//         this.name = name;
//         this.subject = subject;
//         this.age = age;
//         this.num = num;
//     }

//     public void show() {
//         System.out.println(name + " " + subject + " " + age + " " + num);
//     }
// }

class Circle {
    private double x;
    private double y;
    private int r;

    Circle(double x, double y, int r) {
        this.x = x;
        this.y = y;
        this.r = r;
    }

    void show() {
        System.out.println(x + " " + y + " " + r);
    }
}

public class Main {

    public static void main(String[] args) throws IOException {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        Circle[] circles = new Circle[3];
        for (int i = 0; i < circles.length; i++) {
            StringTokenizer st = new StringTokenizer(br.readLine());
            double x = Double.parseDouble(st.nextToken());
            double y = Double.parseDouble(st.nextToken());
            int r = Integer.parseInt(st.nextToken());
            circles[i] = new Circle(x, y, r);
        }

        for (int i = 0; i < circles.length; i++) {
            circles[i].show();
        }

        // Person p = new Person("Jack", "computer", 20, 123);
        // p.show();

        // ObjectOutputStream oos = new ObjectOutputStream(new BufferedOutputStream(new
        // FileOutputStream("test.dat")));

        // try {
        // oos.writeObject(p);
        // oos.flush();
        // } catch (Exception e) {
        // // TODO: handle exception
        // }
        // ObjectInputStream ois = new ObjectInputStream(new BufferedInputStream(new
        // FileInputStream("test.dat")));
        // Person test = null;
        // try {
        // test = (Person) ois.readObject();
        // } catch (Exception e) {
        // // TODO: handle exception
        // }
        // test.show();
    }
}