/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ezen.academy;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;

import javax.swing.*;

// class Gen<T> {
//     T type1;
//     T type2;

//     Gen(T type1, T type2) {
//         this.type1 = type1;
//         this.type2 = type2;
//     }

//     T one() {
//         return type1;
//     }

//     T two() {
//         return type2;
//     }

//     boolean three() {
//         if (type1.equals(type2)) {
//             return true;
//         }
//         return false;
//     }
// }
// class Listener implements ActionListener {
//     public void actionPerformed(ActionEvent e) {
//         JButton jbtn = (JButton) e.getSource();

//         if (jbtn.getText().equals("버튼1")) {
//             jbtn.setText("버튼4");
//         } else {
//             jbtn.setText("버튼1");
//         }
//     }
// }

class Frame extends JFrame {
    Frame() {
        super("JAVA");
        setVisible(true);

        JButton okJbtn = new JButton("ok");
        JButton cancelJbtn = new JButton("cancel");

        Container container = getContentPane();
        container.add(okJbtn);
        container.add(cancelJbtn);

        cancelJbtn.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent arg0) {
                cancelJbtn.setEnabled(false);
            }

            // @Override
            // public void actionPerformed(ActionEvent arg0) {
            // if (jbtn1.getText().equals("버튼1")) {
            // jbtn1.setText("버튼4");
            // } else {
            // jbtn1.setText("버튼1");
            // }
            // }

        });

        container.setLayout(new FlowLayout());
    }
}

public class Main {

    public static void main(String[] args) throws IOException {
        Frame frame = new Frame();

        // HashMap<String, Integer> map = new HashMap<String, Integer>();
        // map.put("홍길동", 21);
        // map.put("엄준식", 24);
        // map.put("카요코", 17);

        // Scanner scan = new Scanner(System.in);

        // System.out.println(map.get(scan.next()));

        // ArrayList<Integer> arrList = new ArrayList<>();

        // for (int i = 0; i < 10; i++) {
        // int num = (int) (Math.random() * 100) + 1;
        // arrList.add(num);
        // }

        // Iterator<Integer> iterator = arrList.iterator();
        // while (iterator.hasNext()) {
        // int input = iterator.next();
        // System.out.println(input);
        // }

        // HashMap<Integer, String> hash = new HashMap<>();
        // hash.put(1, "one");
        // hash.put(2, "two");
        // hash.put(3, "three");

        // (Integer i : hash.keySet()) {
        // System.out.println(i + hash.get(i));
        // }

        // Scanner scan = new Scanner(System.in);

        // e (true) {
        // System.out.print("숫자 입력 (0 종료) : ");
        // int num = scan.nextInt();
        // num == 0)
        // break;
        // System.out.println(hash.get(num));
        // }

        // LinkedList<String> linkedList = new LinkedList<>();
        // linkedList.add("one");
        // linkedList.add("two");
        // linkedList.add("three");

        // Iterator<String> iterator = linkedList.iterator();

        // while (true) {
        // if (!iterator.hasNext())
        // break;
        // String str = iterator.next();
        // if (str.compareTo("three") == 0)
        // iterator.remove();
        // else
        // System.out.println(str);
        // }

        // Gen<String> g = new Gen<String>("seoul", "busan");
        // System.out.println(g.one());
        // System.out.println(g.two());
        // System.out.println(g.three());
    }
}
